// layout共通のCSSよみこみ
import './globals.css'
// https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kurashiru Hiaku Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header></header>
        {children}
      </body>
    </html>
  )
}
